spring:
  cloud:
    config:
      enabled:
        false
  application:
    name:
      user-service
    jpa:
      hibernate:
        ddl-auto:
          create
      generate-ddl:
        true
      defer-datasource-initialization:
        true
